//Array of settings
const setting = [
    "A bustling medieval marketplace",
  "A remote desert oasis",
  "An abandoned amusement park",
  "A futuristic cityscape with flying cars",
  "A tranquil forest glade",
  "A secret underground bunker",
  "A haunted mansion on a hill",
  "A sunken shipwreck in the ocean depths",
  "A magical castle in the clouds",
  "An alien planet with bioluminescent flora",
  "A dystopian society ruled by technology",
  "A snowy mountain peak",
  "A bustling space station orbiting a distant planet",
  "A hidden temple deep in the jungle",
  "A post-apocalyptic wasteland",
  "A cozy cabin nestled in the woods",
  "A mysterious labyrinthine cave system",
  "A sprawling underwater city",
  "A quaint village by the seaside",
  "An enchanted garden filled with mythical creatures",
  "A lunar colony on the moon",
  "A steampunk-inspired metropolis",
  "A time-traveling spaceship",
  "A parallel dimension where magic reigns supreme",
  "A vibrant coral reef teeming with marine life",
  "A medieval castle besieged by invaders",
  "A ghost town in the Old West",
  "A high-tech laboratory conducting groundbreaking experiments",
  "A nomadic caravan crossing a vast desert",
  "An ancient ruins shrouded in mystery",
  "A bustling train station in a bustling city",
  "A fantastical realm hidden behind a magical portal",
  "A sprawling savannah inhabited by exotic wildlife",
  "A remote island inhabited by a reclusive tribe",
  "A network of interconnected treehouses in the rainforest canopy",
  "A lunar research facility on the dark side of the moon",
  "A hidden valley untouched by civilization",
  "A parallel universe where reality is distorted",
  "A futuristic underwater research station",
  "A top-secret government facility hidden beneath a mountain",
  "A medieval tournament ground",
  "A city submerged by rising sea levels",
  "A time-looped town stuck in a perpetual day",
  "A space colony orbiting a distant planet",
  "An intergalactic trading hub bustling with activity",
  "A cursed swamp haunted by vengeful spirits",
  "A floating city in the sky",
  "A labyrinth of ice caves in the Arctic",
  "A virtual reality simulation gone awry",
  "A hidden valley inhabited by mythical creatures"
];

//Array of characters
const characters = [
    "James",
  "John",
  "Robert",
  "Michael",
  "William",
  "David",
  "Richard",
  "Joseph",
  "Charles",
  "Thomas",
  "Daniel",
  "Matthew",
  "Christopher",
  "Andrew",
  "Joshua",
  "Paul",
  "Mark",
  "Steven",
  "Kenneth",
  "Kevin",
  "Brian",
  "George",
  "Edward",
  "Ronald",
  "Timothy",
  "Jason",
  "Jeffrey",
  "Ryan",
  "Jacob",
  "Larry",
  "Frank",
  "Scott",
  "Eric",
  "Stephen",
  "Raymond",
  "Gregory",
  "Joshua",
  "Dennis",
  "Jerry",
  "Walter",
  "Patrick",
  "Peter",
  "Harold",
  "Douglas",
  "Henry",
  "Carl",
  "Arthur",
  "Jack",
  "Mary",
  "Patricia",
  "Jennifer",
  "Linda",
  "Elizabeth",
  "Barbara",
  "Susan",
  "Jessica",
  "Sarah",
  "Karen",
  "Nancy",
  "Margaret",
  "Lisa",
  "Betty",
  "Dorothy",
  "Sandra",
  "Ashley",
  "Kimberly",
  "Donna",
  "Emily",
  "Michelle",
  "Carol",
  "Amanda",
  "Melissa",
  "Deborah",
  "Stephanie",
  "Rebecca",
  "Laura",
  "Sharon",
  "Cynthia",
  "Kathleen",
  "Amy",
  "Shirley",
  "Angela",
  "Helen",
  "Anna",
  "Brenda",
  "Pamela",
  "Nicole",
  "Emma",
  "Samantha",
  "Katherine",
  "Christine",
  "Debra",
  "Rachel",
  "Catherine",
  "Carolyn",
  "Janet",
  "Ruth",
  "Maria"
]

//Array of conflicts
const conflict = [
  "The protagonist must confront their inner demons and overcome their own fears.",
  "A betrayal by a trusted ally threatens to derail the protagonist's plans.",
  "The antagonist possesses a weapon of mass destruction that could annihilate entire civilizations.",
  "The protagonist's moral code is tested when they are forced to make a difficult decision.",
  "A long-standing rivalry between two characters erupts into open conflict, endangering those around them.",
  "The antagonist seeks revenge for past grievances, relentlessly pursuing the protagonist.",
  "The protagonist is haunted by a dark secret from their past that threatens to unravel everything they've built.",
  "A power struggle within the protagonist's group threatens to tear them apart from within.",
  "The antagonist manipulates the protagonist's loved ones, turning them against them.",
  "The protagonist's quest for justice puts them at odds with the authorities, forcing them to go on the run.",
  "A natural disaster strikes, leaving the protagonist and their allies stranded and vulnerable.",
  "The antagonist unleashes a deadly virus that threatens to wipe out humanity.",
  "The protagonist's mentor betrays them, leading to a crisis of faith and identity.",
  "A misunderstanding leads to a conflict between the protagonist and their closest friend.",
  "The antagonist kidnaps the protagonist's loved one, using them as leverage to force their compliance.",
  "The protagonist's quest for vengeance consumes them, blinding them to the consequences of their actions.",
  "A prophecy foretells the protagonist's downfall, and they must defy fate to change their destiny.",
  "The antagonist gains control of a powerful artifact that grants them godlike powers.",
  "The protagonist's loyalty is tested when they discover a shocking truth about their allies.",
  "A love triangle forms between the protagonist and two other characters, leading to jealousy and betrayal.",
  "The antagonist launches a full-scale invasion, overwhelming the protagonist's defenses.",
  "The protagonist's closest ally is revealed to be a traitor, endangering the entire group.",
  "A curse placed upon the protagonist threatens to consume them unless they find a way to break it.",
  "The antagonist creates a false flag operation to frame the protagonist for a crime they didn't commit.",
  "The protagonist's quest for redemption leads them into conflict with their own inner demons.",
  "A prophecy predicts that the protagonist will bring about the end of the world, turning them into a pariah.",
  "The antagonist forms an alliance with other villains, creating a formidable coalition against the protagonist.",
  "The protagonist is blackmailed into committing a heinous act by a shadowy figure from their past.",
  "A love interest is torn between their loyalty to the protagonist and their duty to their people.",
  "The antagonist uses mind control to manipulate the protagonist's allies, turning them against each other.",
  "The protagonist is plagued by doubt and uncertainty, questioning whether they are truly worthy of their quest.",
  "A deadly curse is unleashed upon the land, threatening to wipe out all life unless the protagonist can find a cure.",
  "The antagonist discovers the protagonist's weakness and exploits it to gain the upper hand.",
  "The protagonist's quest for vengeance leads them down a dark path, blurring the line between right and wrong.",
  "The antagonist captures the protagonist's mentor, using them as bait to lure the protagonist into a trap.",
  "The protagonist is framed for a crime they didn't commit, forcing them to clear their name and prove their innocence.",
  "A prophecy predicts that the protagonist's destiny is intertwined with the antagonist's, leading to a final showdown.",
  "The antagonist unleashes a horde of monsters upon the protagonist's city, plunging it into chaos.",
  "The protagonist's allies turn against them when they learn the truth about a past betrayal.",
  "The antagonist gains control of the protagonist's mind, turning them into a puppet to do their bidding.",
  "The protagonist's powers begin to consume them, threatening to transform them into the very thing they fight against.",
  "A bitter rivalry between two factions threatens to escalate into all-out war, with the protagonist caught in the middle.",
  "The antagonist poisons the protagonist's reputation, turning the people against them and making them an outcast.",
  "The protagonist's mentor sacrifices themselves to save the protagonist, leaving them to face their greatest challenge alone.",
  "The antagonist steals the protagonist's most prized possession, using it as leverage to force their surrender.",
  "The protagonist's past comes back to haunt them when an old enemy resurfaces, seeking revenge for past defeats."
]

//Array of resolutions
const resolution = [
  "The protagonist embarks on a new adventure, eager to explore uncharted territories and discover new wonders.",
  "A long-lost friendship is rekindled, bringing joy and happiness to both parties involved.",
  "The protagonist achieves their lifelong dream, proving that hard work and determination can lead to success.",
  "A family torn apart by tragedy finds healing and reconciliation, learning to cherish each moment together.",
  "The protagonist learns to embrace change and adapt to new circumstances, finding strength in their ability to overcome challenges.",
  "A lost treasure is uncovered, bringing wealth and prosperity to those who discover it.",
  "The protagonist finds closure in a past trauma, allowing them to finally move forward and find peace.",
  "A new friendship is forged, creating a bond that will last a lifetime.",
  "The protagonist's perseverance pays off as they overcome obstacles and achieve their goals.",
  "A once-broken community comes together to rebuild and create a better future for generations to come.",
  "The protagonist discovers a hidden talent within themselves, unlocking new possibilities and opportunities.",
  "A long-awaited reunion brings joy and happiness to those who have been separated for far too long.",
  "The protagonist learns to let go of their past regrets and embrace the present moment, finding happiness in the here and now.",
  "A new chapter begins as the protagonist sets out on a journey of self-discovery and personal growth.",
  "The protagonist finds love in unexpected places, opening their heart to new possibilities and experiences.",
  "A promise made long ago is finally fulfilled, bringing closure to a chapter in the protagonist's life.",
  "The protagonist learns to forgive themselves for past mistakes, embracing their imperfections and moving forward with confidence.",
  "A long-standing feud is resolved, paving the way for reconciliation and forgiveness.",
  "The protagonist finds solace in nature, reconnecting with the world around them and finding peace in its beauty.",
  "A long-lost family member is reunited with their loved ones, bringing joy and happiness to all.",
  "The protagonist discovers the true meaning of friendship, realizing that true friends will always stand by their side.",
  "A new arrival brings hope and optimism to a community in need, inspiring others to work together towards a common goal.",
  "The protagonist learns to appreciate the small moments in life, finding joy in the little things that make life worth living.",
  "A forgotten promise is remembered and fulfilled, restoring faith and trust in the protagonist's relationships.",
  "The protagonist's determination inspires others to follow their lead, creating positive change in their community.",
  "A long-held dream is finally realized, proving that anything is possible with hard work and dedication.",
  "The protagonist finds strength in their vulnerability, learning to embrace their emotions and express themselves authentically.",
  "A chance encounter leads to a lifelong friendship, enriching the lives of both parties involved.",
  "The protagonist learns to overcome their fears and insecurities, stepping out of their comfort zone and embracing new experiences.",
  "A new arrival brings unexpected challenges, forcing the protagonist to adapt and grow in order to overcome them.",
  "The protagonist finds peace in solitude, taking time to reflect on their journey and appreciate the beauty of the world around them.",
  "A long-standing grudge is finally put to rest, allowing both parties to move forward and find closure.",
  "The protagonist discovers a newfound sense of purpose, dedicating themselves to a cause greater than themselves.",
  "A forgotten tradition is revived, bringing joy and nostalgia to those who remember its significance.",
  "The protagonist learns the importance of forgiveness, both for themselves and for others, finding healing in the process.",
  "A once-in-a-lifetime opportunity presents itself, allowing the protagonist to fulfill a lifelong dream.",
  "The protagonist learns to find beauty in imperfection, embracing the messy and chaotic aspects of life with open arms.",
  "A new arrival brings excitement and adventure to the protagonist's life, challenging them to step outside of their comfort zone.",
  "The protagonist discovers the power of vulnerability, learning to open up and connect with others on a deeper level.",
  "A forgotten promise is remembered and honored, strengthening the bond between the protagonist and their loved ones.",
  "The protagonist learns to let go of their need for control, surrendering to the flow of life and finding peace in the process.",
  "A new friendship blossoms, bringing laughter and joy to the protagonist's life.",
  "The protagonist discovers the value of patience and perseverance, realizing that good things come to those who wait.",
  "A long-lost treasure is unearthed, bringing joy and excitement to those who uncover it.",
  "The protagonist learns to embrace their uniqueness, celebrating the qualities that make them who they are.",
  "A forgotten memory is rediscovered, bringing clarity and understanding to the protagonist's past.",
  "The protagonist finds closure in an unexpected place, allowing them to finally let go of their past and move forward with their life."
]



//Returns between 2-4 random character names
const randCharacters = () => {
  const numOfCharacters = Math.floor(Math.random() * 3) + 2;

  let result = [];

  for (let i = 0; i < numOfCharacters; i++) {
    const randIndex = Math.floor(Math.random() * characters.length);
    result.push(characters[randIndex]);
  }
  
  const finalList = result.join(', ');

  return finalList
}


//Formats the story with a setting, the characters, a conflict, and a resolution
const formatStory = () => {
  const randSetting = setting[Math.floor(Math.random() * setting.length)];
  const characterSet = randCharacters();
  const randConflict = conflict[Math.floor(Math.random() * conflict.length)];
  const randResolution = resolution[Math.floor(Math.random() * resolution.length)];

  const combined = `Setting: ${randSetting}\nCharacters: ${characterSet}\nConflict: ${randConflict}\nResolution: ${randResolution}`;

  return combined;
}

console.log(formatStory());