const setting = [
    "A bustling medieval marketplace",
  "A remote desert oasis",
  "An abandoned amusement park",
  "A futuristic cityscape with flying cars",
  "A tranquil forest glade",
  "A secret underground bunker",
  "A haunted mansion on a hill",
  "A sunken shipwreck in the ocean depths",
  "A magical castle in the clouds",
  "An alien planet with bioluminescent flora",
  "A dystopian society ruled by technology",
  "A snowy mountain peak",
  "A bustling space station orbiting a distant planet",
  "A hidden temple deep in the jungle",
  "A post-apocalyptic wasteland",
  "A cozy cabin nestled in the woods",
  "A mysterious labyrinthine cave system",
  "A sprawling underwater city",
  "A quaint village by the seaside",
  "An enchanted garden filled with mythical creatures",
  "A lunar colony on the moon",
  "A steampunk-inspired metropolis",
  "A time-traveling spaceship",
  "A parallel dimension where magic reigns supreme",
  "A vibrant coral reef teeming with marine life",
  "A medieval castle besieged by invaders",
  "A ghost town in the Old West",
  "A high-tech laboratory conducting groundbreaking experiments",
  "A nomadic caravan crossing a vast desert",
  "An ancient ruins shrouded in mystery",
  "A bustling train station in a bustling city",
  "A fantastical realm hidden behind a magical portal",
  "A sprawling savannah inhabited by exotic wildlife",
  "A remote island inhabited by a reclusive tribe",
  "A network of interconnected treehouses in the rainforest canopy",
  "A lunar research facility on the dark side of the moon",
  "A hidden valley untouched by civilization",
  "A parallel universe where reality is distorted",
  "A futuristic underwater research station",
  "A top-secret government facility hidden beneath a mountain",
  "A medieval tournament ground",
  "A city submerged by rising sea levels",
  "A time-looped town stuck in a perpetual day",
  "A space colony orbiting a distant planet",
  "An intergalactic trading hub bustling with activity",
  "A cursed swamp haunted by vengeful spirits",
  "A floating city in the sky",
  "A labyrinth of ice caves in the Arctic",
  "A virtual reality simulation gone awry",
  "A hidden valley inhabited by mythical creatures"
];

const characters = [
    "James",
  "John",
  "Robert",
  "Michael",
  "William",
  "David",
  "Richard",
  "Joseph",
  "Charles",
  "Thomas",
  "Daniel",
  "Matthew",
  "Christopher",
  "Andrew",
  "Joshua",
  "Paul",
  "Mark",
  "Steven",
  "Kenneth",
  "Kevin",
  "Brian",
  "George",
  "Edward",
  "Ronald",
  "Timothy",
  "Jason",
  "Jeffrey",
  "Ryan",
  "Jacob",
  "Larry",
  "Frank",
  "Scott",
  "Eric",
  "Stephen",
  "Raymond",
  "Gregory",
  "Joshua",
  "Dennis",
  "Jerry",
  "Walter",
  "Patrick",
  "Peter",
  "Harold",
  "Douglas",
  "Henry",
  "Carl",
  "Arthur",
  "Jack",
  "Mary",
  "Patricia",
  "Jennifer",
  "Linda",
  "Elizabeth",
  "Barbara",
  "Susan",
  "Jessica",
  "Sarah",
  "Karen",
  "Nancy",
  "Margaret",
  "Lisa",
  "Betty",
  "Dorothy",
  "Sandra",
  "Ashley",
  "Kimberly",
  "Donna",
  "Emily",
  "Michelle",
  "Carol",
  "Amanda",
  "Melissa",
  "Deborah",
  "Stephanie",
  "Rebecca",
  "Laura",
  "Sharon",
  "Cynthia",
  "Kathleen",
  "Amy",
  "Shirley",
  "Angela",
  "Helen",
  "Anna",
  "Brenda",
  "Pamela",
  "Nicole",
  "Emma",
  "Samantha",
  "Katherine",
  "Christine",
  "Debra",
  "Rachel",
  "Catherine",
  "Carolyn",
  "Janet",
  "Ruth",
  "Maria"
]

const conflict = [

]

const resolution = [

]